foodDance_web/foodDance_web/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('fooddance.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

foodDance_web/fooddance/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from . import views
from django.urls import reverse


app_name = 'fooddance'

urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<slug:recipe_title_slug>/', views.detail, name="detail"),
    path('detail/<slug:recipe_title_slug>/*', views.detail),
    path('login/', views.user_login, name="user_login"),
    path('register/', views.user_register, name="user_register"),
    path('allrecipes/', views.category_allrecipes, name="all_recipes"),
    path('search/', views.search, name="search"),
    path('logout/', views.user_logout, name="logout"),
    path('like/', views.like, name="like"),
    path('collect/', views.collect, name="collect"),
    path('share/', views.share, name="share"),
    path('confirm/', views.user_confirm, name="confirm"),
    path('myrecipe/',views.myrecipes, name="my_recipes"),
    # path('mycollection/',name="my_collection")


]

foodDance_web/fooddance/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator, MaxValueValidator
from django.template.defaultfilters import slugify


# Create your models here.


class Recipe(models.Model):
    """
    The main content of recipes.
    """
    TITLE_MAX_LENGTH = 50
    OVERVIEW_MAX_LENGTH = 500

    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    image = models.ImageField(upload_to='recipes')
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    overview = models.CharField(max_length=OVERVIEW_MAX_LENGTH)
    duration = models.IntegerField()
    budget = models.IntegerField()
    # difficulty is  0-5
    difficulty = models.FloatField(validators=[MinValueValidator(0), MaxValueValidator(5)])
    pub_date = models.DateField()
    slug = models.SlugField(unique=True)

    views = models.IntegerField(default=0)
    shares = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        import datetime
        self.pub_date = datetime.date.today()
        super(Recipe, self).save(*args, **kwargs)

    def __str__(self):
        return self.slug


class Materials(models.Model):
    """
    The materials(ingredients) of recipes.
    """
    INGREDIENT_MAX_LENGTH = 128
    WEIGHT_MAX_LENGTH = 128

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    ingredient = models.CharField(max_length=INGREDIENT_MAX_LENGTH)
    weight = models.CharField(max_length=WEIGHT_MAX_LENGTH)

    def __str__(self):
        return self.ingredient


class RecipeStep(models.Model):
    """
    The cool steps of recipes.
    """
    CONTENT_MAX_LENGTH = 2000

    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    index = models.IntegerField()
    image = models.ImageField(upload_to='recipes', blank=True)
    content = models.CharField(max_length=CONTENT_MAX_LENGTH)

    def save(self, *args, **kwargs):
        if not self.index or self.index == 0:
            self.index = RecipeStep.objects.filter(recipe=self.recipe).count() + 1
        super(RecipeStep, self).save(*args, **kwargs)

    def __str__(self):
        return self.recipe.slug + "-" + str(self.index)


class Comment(models.Model):
    """
    Comments of recipes
    """
    COMMENT_MAX_LENGTH = 500
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)], default=0)
    content = models.CharField(max_length=COMMENT_MAX_LENGTH, default="")
    like = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username + " - rating:" + str(self.rating)


class UserProfile(models.Model):
    """
    The profile of a user.
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='avatars', blank=True)
    introduction = models.URLField(blank=True)
    twitter_link = models.URLField(blank=True)
    facebook_link = models.URLField(blank=True)

    collections = models.ManyToManyField(Recipe, related_name="user_collections")

    has_confirmed = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username


class ConfirmString(models.Model):
    """
    The confirmation code of a unconfirmed user
    """
    code = models.CharField(max_length=256)
    user = models.OneToOneField(UserProfile, on_delete=models.CASCADE)
    creat_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.user.username + ":   " + self.code

    class Meta:
        ordering = ["-creat_time"]
        verbose_name = "Confirm code"

foodDance_web/fooddance/forms.py
from django.contrib.auth.models import User
from .models import *
from django import forms


class CommentForm(forms.ModelForm):
    rating = forms.ChoiceField(initial=0,
                               choices=((1, 1), (2, 2), (3, 3), (4, 4), (5, 5)), help_text="Rating:", required=True)
    content = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control'}), max_length=Comment.COMMENT_MAX_LENGTH,
                             help_text="Please type your comments:", required=True)

    class Meta:
        model = Comment
        fields = ('rating', 'content')

foodDance_web/fooddance/views.py
from django.shortcuts import render
from .models import Recipe, UserProfile, Comment, RecipeStep
from django.db.models import Avg
from .forms import *
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.models import User
from django.http import JsonResponse, HttpResponse
from django.conf import settings
from django.core.mail import send_mail
import datetime
import hashlib


# Create your views here.

def getAvg(recipe_id):
    avg = Comment.objects.filter(recipe__id=recipe_id).aggregate(Avg('rating'))['rating__avg']
    return int(avg) if avg else 0


def index(request):
    """
    The home page.
    """
    recipes = []
    for recipe in Recipe.objects.all():
        recipes.append(
            dict2obj({
                "title": recipe.title,
                "avg": getAvg(recipe.id),
                "image": recipe.image,
                "during": recipe.duration,
                "author": recipe.author,
                "slug": recipe.slug,
            })
        )

    def takeAverage(ele):
        return ele.avg
    # sort the list by avg
    recipes.sort(key=takeAverage)

    recipes.reverse()
    context_dict = {'recipes': recipes[:9]}

    wrapMessage(request, context_dict)

    return render(request, 'fooddance/index.html', context_dict)


def category_allrecipes(request):
    """
    A view show all recipes
    """
    recipes = []

    def takeAverage(ele):
        return ele.avg

    for recipe in Recipe.objects.all():
        recipes.append(
            dict2obj({
                "title": recipe.title,
                "avg": getAvg(recipe.id),
                "image": recipe.image,
                "during": recipe.duration,
                "author": recipe.author,
                "slug": recipe.slug,
            })
        )
    recipes.sort(key=takeAverage)
    context_dict = {'recipes': recipes}

    return render(request, 'fooddance/category_allrecipes.html', context_dict)


def search(request):
    recipes = []

    def takeAverage(ele):
        return ele.avg

    if request.method == 'GET' and request.GET:
        keyword = request.GET.get("search").lower()
        # keywordlist = recivedKey.title.split(" ")
        for recipe in Recipe.objects.all():
            titleList = recipe.title.lower().split(" ")
            # titleList = titleLower.split(" ")

            if keyword in titleList:
                recipes.append(
                    dict2obj({
                        "title": recipe.title,
                        "avg": getAvg(recipe.id),
                        "image": recipe.image,
                        "author": recipe.author,
                        "overview": recipe.overview,
                        "comments": len(Comment.objects.filter(recipe__id=recipe.id)),
                        "likes": Comment.objects.filter(recipe__id=recipe.id).count(),
                        "views": recipe.views,
                        "slug": recipe.slug,
                        "author_profile": UserProfile.objects.get(user_id=recipe.author.id),
                    })
                )
    context_dict = {'recipes': recipes}
    return render(request, 'fooddance/search.html', context_dict)


def detail(request, recipe_title_slug):
    if request.method == 'POST':
        recipe = Recipe.objects.get(slug=recipe_title_slug)
        rating = request.POST.get('ratingRadioOptions')
        content = request.POST.get('content')

        comment = Comment.objects.get_or_create(user=request.user, recipe=recipe)[0]

        if content:
            comment.content = content

        if rating:
            comment.rating = rating

        comment.save()
        return redirect(reverse('fooddance:detail', kwargs={'recipe_title_slug': recipe_title_slug}))

    context_dict = {}

    showComment = False
    showRating = False

    try:
        recipe = Recipe.objects.get(slug=recipe_title_slug)
        recipe.views = recipe.views + 1
        recipe.save()

        relating_comments = Comment.objects.filter(recipe__id=recipe.id)

        context_dict['recipe'] = recipe
        context_dict['likes'] = relating_comments.filter(like=True).count()
        context_dict['author_profile'] = UserProfile.objects.get(user_id=recipe.author.id)
        avg = relating_comments.aggregate(Avg('rating'))['rating__avg']
        context_dict['avg'] = int(avg) if avg else 0
        context_dict['collect'] = UserProfile.objects.filter(collections__slug=recipe.slug).count()
        context_dict['steps'] = RecipeStep.objects.filter(recipe_id=recipe.id)
        context_dict['comments'] = relating_comments
        context_dict['materials'] = Materials.objects.filter(recipe__id=recipe.id)

        if request.user.is_authenticated:
            context_dict['hasCollect'] = UserProfile.objects.get(user=request.user). \
                                             collections.filter(slug=recipe_title_slug).count() > 0
            try:
                comment = Comment.objects.get(recipe=recipe, user=request.user)
                context_dict['hasLike'] = comment.like
            except Comment.DoesNotExist:
                context_dict['hasLike'] = False

            show_comment = True
            show_rating = True

            try:
                comment = Comment.objects.get(recipe__slug=recipe_title_slug, user__id=request.user.id)
            except Comment.DoesNotExist:
                comment = None

            if comment and len(comment.content) != 0:
                show_comment = False

            if comment and int(comment.rating) > 0:
                show_rating = False

            context_dict['showComment'] = show_comment
            context_dict['showRating'] = show_rating

    except Recipe.DoesNotExist:
        return HttpResponse('recipe does not exist')

    return render(request, 'fooddance/detail.html', context=context_dict)


def user_register(request):
    context_dict = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')

        username_check = False
        email_check = False

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            username_check = True
        finally:
            try:
                User.objects.get(email=email)
            except User.DoesNotExist:
                email_check = True

        if not email_check and not username_check:
            context_dict['error'] = 'The email and username has already been used!'
        elif not email_check:
            context_dict['error'] = 'The email has already been used!'
        elif not username_check:
            context_dict['error'] = 'The username is already exist!'
        else:
            user = User.objects.create(username=username)
            user.set_password(password)
            user.email = email
            user.is_staff = True
            user.is_superuser = True

            user.save()

            up = UserProfile.objects.get_or_create(user=user)[0]
            up.save()

            update_session_handler(request, 'successfully register, please check our email for confirmation!!!')

            code = make_confirm_string(user)
            send_confirmation_email(email, code)

            return redirect(reverse('fooddance:user_login'))

    return render(request, 'fooddance/register.html', context_dict)


def user_login(request):
    """
    login view
    """
    context_dict = {}

    if request.user.is_authenticated:
        update_session_handler(request, "You are logged in.")
        return redirect(reverse("fooddance:index"))

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                try:
                    up = UserProfile.objects.get(user=user)
                    if not up.has_confirmed:
                        context_dict['login_error'] = "Your account has noe been confirmed. Check your email!"
                    else:
                        update_session_handler(request, "successful login")
                        login(request, user)
                        return redirect(reverse('fooddance:index'))
                except UserProfile.DoesNotExist:
                    pass

            else:
                context_dict['login_error'] = "Your account is disabled."
        else:
            context_dict['login_error'] = "Check your username or password."

    wrapMessage(request, context_dict)
    return render(request, 'fooddance/login.html', context=context_dict)


@login_required
def user_logout(request):
    logout(request)
    update_session_handler(request, 'successfully log out')
    return redirect(reverse('fooddance:index'))


def like(request):
    if request.method == 'POST':
        user_id = request.POST.get('user')
        recipe_id = request.POST.get('recipe')

        comment = \
            Comment.objects.get_or_create(user=User.objects.get(id=user_id), recipe=Recipe.objects.get(id=recipe_id))[0]

        if comment and comment.like:
            comment.like = False
            response = JsonResponse({'result': 'dislike'})
        else:
            comment.like = True
            response = JsonResponse({'result': 'like'})
        comment.save()
        return response


def collect(request):
    if request.method == 'POST':
        user = int(request.POST.get('user'))
        recipe = int(request.POST.get('recipe'))

        up = UserProfile.objects.get(user_id=user)

        if up.collections.filter(id=recipe).count() == 0:
            up.collections.add(Recipe.objects.get(id=recipe))
            response = JsonResponse({'result': 'collect'})

foodDance_web/templates/fooddance/b5_base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        FoodDance -
        {% block title_block %}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    {% block css_block %}
    {% endblock %}
    <link href="{% static 'css/b5_base.css' %}" rel="stylesheet">
    <link href="{% static 'css/base.css' %}" rel="stylesheet">
</head>
<body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>


    {% if alert_message  %}
        <div id="alert_message" class="alert alert-warning alert-dismissible fade show" role="alert">
              <strong>{{ alert_message }}</strong>
              <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    {% endif %}

    <div id="header" class="header-block ">
        <div class="row justify-content-end align-items-end">
           {% if user.is_authenticated %}
                <div class="col-md-2 dropdown">
                    <a class="btn dropdown-toggle login_text fs-6" href="{% url 'fooddance:index' %}" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
                        Welcome, {{ user.username }} !
                    </a>

                    <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'fooddance:my_recipes' %}">My Recipe</a></li>
                        <li><a class="dropdown-item" href="../../admin/fooddance/recipe/add/">Add Recipe</a></li>
                    </ul>
                </div>
{#                <div class="col-md-1 col-sm-2 logout_grid"><a href="" class="login_text fs-6 text-center">My Profile</a></div>#}
{#                <div class="col-md-1 col-sm-2 logout_grid"><a href="admin/fooddance/recipe/add/" class="login_text fs-6 text-center">Add Recipe</a></div>#}
                <div class="col-md-1 btn">
                    <img src={% static 'images/logout.svg' %}/>
                    <a href="{% url 'fooddance:logout' %}" class="login_text">Log-Out</a>
                </div>
                <div class="col-md-1"></div>

            {% else %}
                <div class="col-md-1 btn">
                    <a href="{% url 'fooddance:user_login' %}" class="login_text">Login</a>
                    <img src={% static 'images/login.svg' %}/>
                </div>
                <div class="col-md-1 btn">
                    <a href="{% url 'fooddance:user_register' %}"  class="login_text">Sign-Up</a>
                    <img src={% static 'images/signup.svg' %}/>
                </div>
                <div class="col-md-1"></div>

            {% endif %}
        </div>
        <div>
            <div class="col-md-6"><img src="{% static 'images/logo_white.png' %}" alt="Logo" class="header-img"/></div>
        </div>
        <div class="row justify-content-start">
            <div class="col-3"></div>
            <div class="col-1"><img src="{% static 'images/slogan.png' %}" alt="Slogan" width="400px"/></div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid row justify-content-end">
                 <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarText">
                <ul class="col-7 navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item col-md-1">
                    </li>
                    <li class="nav-item col-md-3 col-sm-12">
                        <a class="nav-link fs-6 text-center button-category  fs-4" aria-current="page" href="{% url 'fooddance:index' %}">HOME</a>
                    </li>
                    <li class="nav-item col-md-3 col-sm-12">
                        <a class="nav-link fs-6 text-center button-category  fs-4" href="{% url 'fooddance:all_recipes' %}">ALL RECIPES</a>
                    </li>
                </ul>
                <form class="col-md-4 col-sm-12 d-flex" method="get" action="{% url 'fooddance:search' %}">
                    <input class="form-control me-3 px-4" type="text" placeholder="Search" aria-label="Search" name="search">
                    <button class="btn btn-outline-light me-3" type="submit">Search</button>
                </form>
                <div class="col-md-1"></div>
                </div>
            </div>
            </nav>
    </div>

    <div class="container-fluid">
        <div class="row justify-content-center">
            <!-- main content should display in this div -->
            <div  id="mainbox" class="col-lg-8 col-md-10 col-sm-12 mainArea shadow-lg" >
                    {% block body_block %}
                    {% endblock %}
           </div>
        </div>
    </div>

    <div id="footerbox" class="container-fluid">
        <div id="footerrow" class="row justify-content-center">
               <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
                <p class="col-md-4 mb-0 text-muted">© 2021 WedDance@UofG</p>

                <a  href="{% url 'fooddance:index' %}" class="col-md-2 d-flex align-items-center justify-content-end mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                 <img  id="footer_logo" width="40" height="40" src="{% static "images/logo_pink.png" %}">
                </a>

                <a href="https://github.com/WebDance-UofG/FoodDance" class="col-md-2 d-flex align-items-center justify-content-start mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
                     <img width="40" height="40" src="{% static "images/GitHub-Mark-32px.png" %}">
                </a>

                <ul class="nav col-md-4 justify-content-end">
                    <li class="nav-item"><a href="{% url 'fooddance:index' %}" class="nav-link px-2 text-muted">Home</a></li>
                    <li class="nav-item"><a href="{% url 'fooddance:all_recipes' %}" class="nav-link px-2 text-muted">All Recipes</a></li>
                   {% if user.is_authenticated %}
                       <li class="nav-item"><a href="{%  url 'fooddance:logout' %}" class="nav-link px-2 text-muted">Login</a></li>
                   {% else %}
                       <li class="nav-item"><a href="{%  url 'fooddance:user_login' %}" class="nav-link px-2 text-muted">Login</a></li>
                         <li class="nav-item"><a href="{% url 'fooddance:user_register' %}" class="nav-link px-2 text-muted">Sign Up</a></li>
                    {% endif %}
                </ul>
          </footer>
        </div>
    </div>

</body>
</html>

foodDance_web/templates/fooddance/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        FoodDance -
        {% block title_block %}
        {% endblock %}
    </title>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block css_block %}
    {% endblock %}
</head>
<body>
    <div class="header-block">
    <div class="row">
        {% if user.is_authenticated %}
            <div class="col-md-2 col-md-offset-7 logout_grid login_text" >Welcome, Author</div>
            <div class="col-md-1 logout_grid"><a href="" class="login_text">My Profile</a></div>
            <div class="col-md-1 logout_grid"><a href="" class="login_text">Add Recipe</a></div>
            <div class="col-md-1" style="margin-top: 10px"><a href="{% url 'fooddance:logout' %}" class="login_text">Log Out</a></div>
        {% else %}
            <div class="col-md-1 col-md-offset-10 login_grid"><a href=""{% url 'fooddance:user_login' %}"" class="login_text">Login</a></div>
            <div class="col-md-1" style="margin-top: 10px"><a href="{% url 'fooddance:user_register' %}" class="login_text">Sign Up</a></div>
        {% endif %}
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-1"><img src="{% static 'images/logo_white.png' %}" alt="Logo" width="600" style="margin: 5px 0px"/><br/></div>
    </div>
    <div class="row">
        <div class="col-md-3 col-md-offset-3"><h4><b style="color:#ffffff">COOK WITH WORLD</b></h4></div>
        <div class="col-md-5 col-md-offset-1">
            <form method="get" action="{% url 'fooddance:search' %}">
                {% csrf_token%}
                <input type="text" name="search" class="search">
                <input type="submit" name="searchbutton" value="search" class="button-search">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-1"><a href="{% url 'fooddance:index' %}" class="button-category">Home</a></div>
        <div class="col-md-2"><a href="{% url 'fooddance:all_recipes' %}" class="button-category">All Recipe</a></div>
        <div class="col-md-2"><a href="" class="button-category">Difficulty</a></div>
        <div class="col-md-2"><a href="" class="button-category">Time</a></div>
        <div class="col-md-2"><a href="" class="button-category">About</a></div>
    </div>
</div>

{% block body_block %}
{% endblock %}

<hr>
<div>
    <a href="">Facebook</a>
    <a href="">Twitter</a>
</div>

</body>
</html>

foodDance_web/templates/fooddance/index.html
<!doctype html>
{% extends 'fooddance/b5_base.html' %}
{% load staticfiles  %}

{% block title_block %}
    Homepage
{% endblock %}
{% block css_block %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}
{% block body_block %}
    
    <p class="todays-top">Today's Top</p>
    <div class="row justify-content-center">
        <div class="row align-items-center top-recipe-background">
            <div class="col-md-7 col-sm-12">
                <p class="top-recipe-title">Scrambled Egg with Tomato</p>
                <p class="top-recipe-author">@Author</p>
                <div>
                    <img src="{% static 'images/ze-comment-o.svg' %}" class="top-recipe-comment-icon" alt="comment-icon"/>
                    <img src="{% static 'images/comment_stars.png' %}" class="top-recipe-comment-star" alt="comment-star"/>
                    <p class="top-recipe-comment">"Very tasty and easy to cook !! I love this recipe !!"</p>
                </div>
                <div class="top-recipe-detail-div">
                    <img src="{% static 'images/md-access_time.svg' %}" class="top-recipe-icon" alt="time-icon"/>
                    <p class="top-recipe-text">Duration</p>
                    <p class="top-recipe-text">45mins</p>

                </div>
                <div class="top-recipe-detail-div">
                    <img src="{% static 'images/stLine-cup-l Copy.svg' %}" class="top-recipe-icon" alt="diff-icon"/>
                    <p class="top-recipe-text">Difficulty</p>
                    <p class="top-recipe-text">Easy</p>
                </div>
                <div class="top-recipe-detail-div">
                    <img src="{% static 'images/ze-notes-o.svg' %}" class="top-recipe-icon" alt="overview-icon"/>
                    <p class="top-recipe-text">Overview</p>
                    <p class="top-recipe-text">A kind of classic recipes</p>
                </div>
            </div>
            <div class="col-md-5 col-sm-12">
                <img src="{% static 'images/top_recipe_cover_1.png' %}" class="img-fluid" alt="top-img"/>
            </div>
        </div>
    </div>
    <hr>
    <p class="todays-top">Recommendation</p>
    <div class="container-fluid">
        <div class="row">
        {% if recipes %}
            {% for recipe in recipes %}
                <div class="col-md-4 col-sm-6 col-none-12">
                    <a href="{% url 'fooddance:detail' recipe.slug %}" class="card recom-recipe-bg">
                        <div class="card recom-recipe-block1">
                            <img src="{{ MEDIA_URL }}/{{ recipe.image }}" class="card-img-center recom-recipe-pic" alt="recipe-img"/>
                        </div>
                        <div class="recom-recipe-block2">
                            <p class="text-center recom-recipe-title">{{ recipe.title }}</p>
                        </div>
                        <div class="recom-recipe-block3">
                            <div class="row justify-content-center">
                                <div class="col-4">
                                    <img src="{% static 'images/riFill-star-fill.svg' %}" class="recom-recipe-icon" alt="rate-icon"/>
                                    <p class="recom-recipe-text">{{ recipe.avg }}</p>
                                </div>
                                <div class="col-4">
                                    <img src="{% static 'images/md-access_time.svg' %}" class="recom-recipe-icon" alt="time-icon"/>
                                    <p class="recom-recipe-text">{{ recipe.during }} min</p>
                                </div>
                                <div class="col-4">
                                    <img src="{% static 'images/user-icon.svg' %}" class="recom-recipe-icon" alt="user-icon"/>
                                    <p class="recom-recipe-text">{{ recipe.author }}</p>
                                </div>
                            </div>
                        </div>
                    </a>
                </div>
            {% endfor %}
        {% endif %}
        </div>
    </div>
    <div class="col-12"> <a class="btn btn-outline-secondary others-findall" href="{% url 'fooddance:all_recipes' %}" role="button">Click Here, Find More Recipes!</a></div>
{% endblock %}